// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package worddbc

import (
	"database/sql"
)

type ActiveQuestion struct {
	ID     int64
	UserID sql.NullInt64
	WordID sql.NullInt64
	Type   int64
}

type UserWord struct {
	ID           int64
	LastAnswered sql.NullString
	Delay        sql.NullInt64
	Active       int64
	WordID       int64
	UserID       int64
}

type Word struct {
	ID                 int64
	Foreignword        string
	Foreigndescription string
	Nativeword         string
	Nativedescription  string
	Pronunciation      string
	DictionaryID       int64
}
